Focus/Focus/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^$', 'ClientPortal.views.index'),
    url(r'^logout/', 'ClientPortal.views.logout'),
    url(r'^login/', 'ClientPortal.views.login'),
    url(r'^viewJobs/', 'ClientPortal.views.viewJobs'),
    url(r'^viewJobFiles/', 'ClientPortal.views.viewJobFiles'),
    url(r'^viewJobHistory/', 'ClientPortal.views.viewJobHistory'),
    url(r'^home/', 'ClientPortal.views.home'),
    url(r'^getMessage/', 'ClientPortal.views.getMessage'),
    url(r'^getJobDocuments/', 'ClientPortal.views.getJobDocuments'),
    url(r'^getJobHistory/', 'ClientPortal.views.getJobHistory'),
    url(r'^resetAndEmailPassword', 'ClientPortal.views.resetAndEmailPassword'),
    url(r'^forgotPassword', 'ClientPortal.views.forgotPassword'),
    url(r'^getContactsForClient', 'ClientPortal.views.getContactsForClient'),
    url(r'^changePassword', 'ClientPortal.views.changePassword'),
    url(r'^performChangePassword', 'ClientPortal.views.performChangePassword'),
    url(r'^userViewedJobs', 'ClientPortal.views.userViewedJobs'),
    url(r'^userViewedMessage', 'ClientPortal.views.userViewedMessage'),
    url(r'^viewMessages', 'ClientPortal.views.viewMessages'),
    url(r'^clientFiles', 'ClientPortal.views.clientFiles'),
    url(r'^uploadFile', 'ClientPortal.views.uploadFile'),
    url(r'^sendMessage', 'ClientPortal.views.sendMessage'),
    url(r'^clientActivity', 'ClientPortal.views.clientActivity'),
    url(r'^editJob', 'ClientPortal.views.editJob'),
    url(r'^manageJobs', 'ClientPortal.views.manageJobs'),
    url(r'^comments/', include('django.contrib.comments.urls')),
    # url(r'^logout/', 'ClientPortal.views.logout'),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

Focus/ClientPortal/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.db.models.signals import post_save
from django.contrib.auth.models import User
import datetime


class Job(models.Model):
    JOB_STATUS_CHOICES = (
        (1, 'New Job'),
        (2, 'Job Setup Completed'),
        (3, 'Released To Field'),
        (4, 'Field Work Started'),
        (5, 'Field Work Completed'),
        (6, 'Drafting Started'),
        (7, 'Drafting Completed'),
        (8, 'Checking Started'),
        (9, 'Checking Completed'),
        (10, 'Completed'),
        (11, 'Cancelled'),
    )
    JOB_TYPE_CHOICES = (
        (1, 'Pipeline'),
        (2, 'Wellsite'),
        (3, 'Core Hole'),
        (4, 'Right of Way'),
        (5, 'Tower Site'),
        (6, 'Campsite'),
        (7, 'Other'),
    )
    INVOICE_STATUS_CHOICES = (
        (1, 'None'),
        (2, 'Ready'),
        (3, 'Paid'),
    )
    number = models.CharField(max_length=50)
    status = models.IntegerField(choices=JOB_STATUS_CHOICES)
    jobType = models.IntegerField(choices=JOB_TYPE_CHOICES)
    location_surface_from = models.ForeignKey('Location', related_name='surfaceFrom')
    location_bottom_to = models.ForeignKey('Location', related_name='bottomTo')
    client = models.ForeignKey('Client')
    afeNumber = models.CharField(max_length=50, blank=True)
    clientFileNumber = models.CharField(max_length=50, blank=True)
    notes = models.CharField(max_length=500, blank=True)
    startDate = models.DateField()
    expectedCompletionDate = models.DateField()
    lastModifiedDate = models.DateTimeField()
    invoiceStatus = models.IntegerField(choices=INVOICE_STATUS_CHOICES)
    assignedTo = models.CharField(max_length=100)

    def __unicode__(self):
        return self.number

    def save(self, force_insert=False, force_update=False):
        self.lastModifiedDate = datetime.datetime.now()
        super(Job, self).save(force_insert, force_update)


class Location(models.Model):
    # PNG
    QuarterUnit = models.CharField(max_length=1, blank=True, choices=((i, i) for i in ('A', 'B', 'C', 'D')))  # A - D
    Unit = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 101)))  # 1 - 100
    Block = models.CharField(max_length=1, blank=True, choices=((i, i) for i in ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L')))  # A - L
    NTSMapsheet = models.IntegerField(null=True, blank=True, choices=((i, i) for i in (82, 83, 92, 93, 94, 102, 103, 104, 114)))
    Mapsheet1_250 = models.CharField(max_length=1, blank=True, choices=((i, i) for i in ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P')))  # A - P
    Mapsheet1_50 = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 17)))  # 1 - 16
    # ATS
    LSD = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 17)))  # 1 - 16
    Section = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 37)))  # 1 - 36
    Township = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 127)))  # 1 - 126
    Range = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 31)))  # 1 - 30
    Meridian = models.IntegerField(null=True, blank=True, choices=((i, i) for i in range(1, 7)))  # 1 - 6
    # lat / long
    Latitude = models.FloatField()
    Longitude = models.FloatField()

    def __unicode__(self):
        if self.LSD is not None or self.Section is not None or self.Township is not None or self.Range is not None or self.Meridian is not None:
            return xstr(self.LSD) + '-' + xstr(self.Section) + '-' + xstr(self.Township) + '-' + xstr(self.Range) + '-' + xstr(self.Meridian)
            #return 'LSD LOCATION'
        else:
            return self.QuarterUnit + '-' + xstr(self.Unit) + '-' + self.Block + "-" + xstr(self.NTSMapsheet) + "-" + self.Mapsheet1_250 + "-" + xstr(self.Mapsheet1_50)
            #return 'PNG LOCATION'



class UserAccount(models.Model):
    ROLES = (
        (1, 'FocusEmployee'),
        (2, 'FocusPM'),
        (3, 'ClientContact'),
    )
    user = models.OneToOneField(User)
    userId = models.IntegerField(unique=True)
    client = models.ForeignKey('Client', blank=True)
    active = models.BooleanField(default=True)
    role = models.IntegerField(choices=ROLES, blank=True)
    lastViewedJobs = models.DateTimeField()

    def __unicode__(self):
        return self.user.username + " (" + str(self.userId) + ")"


class Client(models.Model):
    clientId = models.IntegerField(max_length=4)
    name = models.CharField(max_length=500)
    logo = models.FileField(upload_to='ClientPortal/static/ClientLogos', blank=True)
    active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name + " (" + str(self.clientId) + ")"


class JobHistory(models.Model):
    job = models.ForeignKey('Job')
    date = models.DateTimeField()
    change = models.CharField(max_length=500)

    def __unicode__(self):
        return self.job.number + " - " + str(self.date) + " - " + self.change


class JobFile(models.Model):
    FILE_TYPES = (
        (1, 'Invoice'),
        (2, 'Plan'),
        (3, 'Misc'),
    )
    dateAdded = models.DateTimeField(auto_now_add=True)
    file = models.FileField(upload_to='ClientPortal/static/Files')
    fileType = models.IntegerField(choices=FILE_TYPES, blank=True)
    job = models.ForeignKey('Job', blank=True)
    isInvoice = models.BooleanField(default=False)

    def __unicode__(self):
        return self.job.number + '-' + self.file.name


class UserActivity(models.Model):
    date = models.DateTimeField()
    user = models.ForeignKey('UserAccount', blank=True)
    action = models.CharField(max_length=500)

    def __unicode__(self):
        return str(self.date) + "-" + self.user.user.email + " - " + self.action


class Message(models.Model):
    date = models.DateTimeField()
    sentFrom = models.ForeignKey('UserAccount', related_name='sentFrom')
    sentTo = models.ForeignKey('UserAccount', related_name='sentTo')
    subject = models.CharField(max_length=400)
    message = models.TextField()
    hasBeenRead = models.BooleanField(default=False)
    attachment = models.FileField(upload_to='ClientPortal/static/MessageAttachments', blank=True)

    def __unicode__(self):
        return str(self.date) + " - from " + self.sentFrom.user.email + " to " + self.sentTo.user.email + " - " + self.subject


def xstr(s):
    return '' if s is None else str(s)


def jobChangedHandler(sender, instance, **kwargs):
    originalJob = Job.objects.filter(number=instance.number)
    if len(originalJob) > 0:
        originalJob = originalJob[0]
        if originalJob.afeNumber != instance.afeNumber:
            history = JobHistory()
            history.date = datetime.datetime.now()
            history.job = originalJob
            history.change = "AFE Number changed from '" + originalJob.afeNumber + "' to '" + instance.afeNumber + "'."
            history.save()
        if originalJob.clientFileNumber != instance.clientFileNumber:
            history = JobHistory()
            history.date = datetime.datetime.now()
            history.job = originalJob
            history.change = "Client File Number changed from '" + originalJob.clientFileNumber + "' to '" + instance.clientFileNumber + "'."
            history.save()
        if originalJob.jobType != instance.jobType:
            history = JobHistory()
            history.date = datetime.datetime.now()
            history.job = originalJob
            history.change = "Job Type changed from '" + originalJob.get_jobType_display() + "' to '" + instance.get_jobType_display() + "'."
            history.save()
        if originalJob.status != instance.status:
            history = JobHistory()
            history.date = datetime.datetime.now()
            history.job = originalJob
            history.change = "Status changed from '" + originalJob.get_status_display() + "' to '" + instance.get_status_display() + "'."
            history.save()


def jobFileChangedHandler(sender, instance, **kwargs):
    history = JobHistory()
    history.date = datetime.datetime.now()
    history.job = instance.job
    history.change = "Added file '" + instance.file.name + "'."
    history.save()


pre_save.connect(jobChangedHandler, sender=Job)
post_save.connect(jobFileChangedHandler, sender=JobFile)

Focus/templates/_clientMenu.html
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/home">Focus Client Portal</a>
        <ul class="nav">
            <li id="menuViewJobs"><a href="/home">Home</a></li>
            <li id="menuJobHistory"><a href="/viewJobHistory">Job History</a></li>
            <li id="menuJobFiles"><a href="/viewJobFiles">Job Files</a></li>
            <li id="menuMapJobs"><a href="http://maps.google.ca/">Map Jobs</a></li>
        </ul>

        <ul class="nav pull-right">
            <li id="menuClientFiles"><a href="/clientFiles"><span class="icon-folder-open"></span></a></li>
            <li id="menuMessages"><a href="/viewMessages"><span class="icon-envelope"></span>{% if unreadMessages > 0 %} {{ unreadMessages }}{% endif %}</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='icon-user'></span> {{ user.user.username }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="/changePassword">Change Password</a></li>
                    <li class="divider"></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>
            <li id="menuHelp"><a href="#"><span class="icon-question-sign"></span></a></li>
        </ul>
    </div>
</div>

Focus/templates/_pmMenu.html
<div class="navbar">
    <div class="navbar-inner">
        <a class="brand" href="/home">Focus Client Portal</a>
        <ul class="nav">
            <li id="menuHome"><a href="/home">Home</a></li>
            <li id="menuJobHistory"><a href="/viewJobHistory">Job History</a></li>
            <li id="menuClientFiles"><a href="/clientFiles">Client Files</a></li>
            <li id="menuClientActivity"><a href="/clientActivity">Client Activity</a></li>

        </ul>

        <ul class="nav pull-right">
            <li id="menuMessages"><a href="/viewMessages"><span class="icon-envelope"></span>{% if unreadMessages > 0 %} {{ unreadMessages }}{% endif %}</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class='icon-user'></span> {{ user.user.username }} <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="/changePassword">Change Password</a></li>
                    <li class="divider"></li>
                    <li><a href="/logout">Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
</div>

Focus/templates/changePassword.html
<!DOCTYPE html>
<html>
<head>
    <title>Focus Client Portal</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/jqplot/jquery.jqplot.css" />
    {% if user.role == 3 %}
        <!--Start of Zopim Live Chat Script-->
        <script type="text/javascript">
            window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
                    d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                    _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
                $.src='//cdn.zopim.com/?1Agr2UfhheuEIAobJEVMxe7YjJyfsyKv';z.t=+new Date;$.
                        type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
        </script>
        <!--End of Zopim Live Chat Script-->
    {% endif %}
</head>
<body>
{% if user.role == 3 %}
    {% include '_clientMenu.html' %}
{% else %}
    {% include '_pmMenu.html' %}
{% endif %}

<div class="container">

    <form class="form-horizontal">

        <div class="control-group">   <label class="control-label">Current Password:</label><div class="controls"> <input type="text" id="currentPassword" name="currentPassword"></div></div>
        <div class="control-group">   <label class="control-label">New Password:</label><div class="controls"> <input type="text" id="newPassword1" name="newPassword1"></div></div>
        <div class="control-group">   <label class="control-label">New Password:</label><div class="controls"> <input type="text" id="newPassword2" name="newPassword2"></div></div>
    {% csrf_token %}
        <div class="control-group">    <div class="controls"> <input class="btn btn-primary" type="submit" value="Submit" onclick="ChangePassword();"></div>        </div>
    </form>


</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

<script type="text/javascript">

    $(document).ready(function(){
    });

    function ChangePassword() {
        var currentPassword = $("#currentPassword").val();
        var newPassword1 = $("#newPassword1").val();
        var newPassword2 = $("#newPassword2").val();
        var csrfToken = $("#csrfmiddlewaretoken").val();
        // disable button & show ajax loading image

        $.ajax(
                {
                    url: '/performChangePassword',
                    type: 'POST',
                    cache: false,
                    async: true,
                    dataType: 'json',
                    data: { 'currentPassword': currentPassword, 'newPassword1': newPassword1, 'newPassword2': newPassword2, 'csrfmiddlewaretoken' : csrfToken },
                    success: function (data) {
                        if(data.success == true)
                            alert("Your password has been changed.");
                        else
                            alert("An error occurred while changing your password: " + data.message);
                        // hide ajax loading image and enable button again
                        // redirect to login page
                    },
                    error: function(data) {
                        console.log("Error setting UserViewedJobs");
                        alert("An error occurred while changing your password.");
                        // hide ajax loading image and enable button again
                    }
                }
        );

    }

</script>

Focus/templates/forgotPassword.html
<!DOCTYPE html>
<html>
<head>
    <title>Focus Client Portal</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}style.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/jqplot/jquery.jqplot.css" />
    <!--Start of Zopim Live Chat Script-->
    <script type="text/javascript">
        window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
                d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
            $.src='//cdn.zopim.com/?1Agr2UfhheuEIAobJEVMxe7YjJyfsyKv';z.t=+new Date;$.
                    type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
    </script>
    <!--End of Zopim Live Chat Script-->
</head>
<body id="loginPage">


<div class="container">
    <div class="form-signin" ><br/>

        <img src="{{ STATIC_URL }}images/focus.png"/><br/>
        <h2 class="form-signin-heading">Password Reset</h2>
        Email address: <input type="text" id="email" name="email"><br/>

        <input class="btn btn-primary" type="submit" value="Submit" onclick="ResetPassword();">
    </div>





</div>
<script src="http://code.jquery.com/jquery.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

<script type="text/javascript">

    $(document).ready(function(){
    });

    function ResetPassword() {
        var email = $("#email").val();
        // disable button & show ajax loading image

        $.ajax(
                {
                    url: '/resetAndEmailPassword/?email=' + email,
                    type: 'GET',
                    cache: false,
                    async: true,
                    dataType: 'json',
                    success: function (data) {
                        alert("An email has been sent to " + email + " with your new password.");
                        // hide ajax loading image and enable button again
                    },
                    error: function(data) {
                        console.log("Error setting UserViewedJobs");
                        alert("An error occurred while resetting your password.");
                        // hide ajax loading image and enable button again
                    }
                }
        );

    }

</script>

Focus/templates/index.html
<!DOCTYPE html>
<html>
<head>
    <title>Focus Client Portal</title>
    <link href="{{ STATIC_URL }}bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link href="{{ STATIC_URL }}style.css" rel="stylesheet" media="screen">
    <!--Start of Zopim Live Chat Script-->
    <script type="text/javascript">
        window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
                d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
            $.src='//cdn.zopim.com/?1Agr2UfhheuEIAobJEVMxe7YjJyfsyKv';z.t=+new Date;$.
                    type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
    </script>
    <!--End of Zopim Live Chat Script-->
</head>
<body id="loginPage">

<div class="container">

    <form class="form-signin" action="/login/" method="post"><br/>
        {% csrf_token %}
        <img src="{{ STATIC_URL }}images/focus.png"/><br/>
        <h2 class="form-signin-heading">Client Portal Login</h2>
        <input type="text" class="input-block-level" placeholder="Email address" id="user" name="user">
        <input type="password" class="input-block-level" placeholder="Password" id="pw" name="pw">
        <a class="pull-right" href="/forgotPassword.html">Forgot password?</a><br/>
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
        {{ message }}
    </form>



    <br/><br/>


</div>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="{{ STATIC_URL }}bootstrap/js/bootstrap.min.js"></script>
</body>
</html>

Focus/templates/viewJobFiles.html
<!DOCTYPE html>
<html>
<head>
    <title>Focus Client Portal</title>
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
    <link rel="stylesheet" type="text/css" href="/static/style.css" />
    <link rel="stylesheet" type="text/css" href="/static/jqplot/jquery.jqplot.css" />
    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/datepicker.css" />
    <link rel="stylesheet" type="text/css" href="/static/DataTables-1.9.4/media/css/jquery.dataTables.css" />
    {% if user.role == 3 %}
        <!--Start of Zopim Live Chat Script-->
        <script type="text/javascript">
            window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
                    d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
                    _.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute('charset','utf-8');
                $.src='//cdn.zopim.com/?1Agr2UfhheuEIAobJEVMxe7YjJyfsyKv';z.t=+new Date;$.
                        type='text/javascript';e.parentNode.insertBefore($,e)})(document,'script');
        </script>
        <!--End of Zopim Live Chat Script-->
    {% endif %}
</head>
<body>

{% if user.role == 3 %}
    {% include '_clientMenu.html' %}
{% else %}
    {% include '_pmMenu.html' %}
{% endif %}

<div class="container-fluid">
    <div class="row-fluid">
        <div class="span2 well">
            <fieldset>
                <legend>Filter Job Files&nbsp;&nbsp; &nbsp;<input class="btn" type="button" value="Clear" onclick="ClearFilter();"></legend>
                Date From: <div data-date-format="mm/dd/yyyy" data-date="" id="filterDateFrom"class="input-append date">
                    <input type="text" class="dateTo jobFilesFilterDate">
                    <span class="add-on"><i class="icon-calendar"></i></span>
                </div><br/>
            Date To:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<div data-date-format="mm/dd/yyyy" data-date="" id="filterDateTo"class="input-append date">
            <input type="text" class="dateTo jobFilesFilterDate">
            <span class="add-on"><i class="icon-calendar"></i></span>
            </div><br/>
            Job:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="filterJob" class="filterField jobFilesFilter"/><br/>
            Type:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="filterType" class="filterField jobFilesFilter"/><br/>
            Name:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="text" id="filterName" class="filterField jobFilesFilter"/><br/>
                </fieldset>
        </div>
        <div class="span10">
            <div id="exportTable" class="pull-right"><button class="btn btn-mini" type="button">PDF</button> <button class="btn btn-mini" type="button">XLS</button></div>
            <table class='table table-bordered table-striped table-hover' id="fileTable">
                <thead>
                    <tr>
                        <td>Date Added</td>
                        <td>Job</td>
                        <td>Type</td>
                        <td>Name</td>
                        <td>Size</td>
                        <td>Sort Date Added</td>
                    </tr>
                </thead>
                <tbody>
                {% for file in files %}
                    <tr>
                        <td>{{ file.dateAdded }}</td>
                        <td>{{ file.job.number }}</td>
                        <td>{{ file.get_fileType_display }}</td>
                        <td><a href="/{{ file.file.name|slice:"13:" }}">{{ file.file.name|slice:"26:" }}</a></td>
                        <td>{{ file.file.size|filesizeformat }}</td>
                        <td>{{ file.dateAdded|date:"Ymd"|lower }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script src="http://code.jquery.com/jquery.js"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="/static/DataTables-1.9.4/media/js/jquery.dataTables.min.js"></script>
<script src="/static/bootstrap/js/bootstrap-datepicker.js"></script>
</body>
</html>

<script type="text/javascript">

$(document).ready(function(){
    $("#menuJobFiles").addClass("active");

    var fileTable=$("#fileTable").dataTable(
            {
                "bPaginate": true,
                "bSearchable": true,
                "bFilter": true,
                "bScrollCollapse": true,
                "aaSorting": [[8, 'desc']],
                "sPaginationType": "full_numbers",
                "iDisplayLength": 20,
                "oTableTools": {
                    "sRowSelect": "single",
                    "aButtons": []
                },
                "aoColumns": [
                    { "sWidth": "180px", "iDataSort" : 5 },
                    { "sWidth": "75px" },
                    { "sWidth": "75px" },
                        null,
                    { "sWidth": "75px" },
                    { "bVisible": false }
                ]
            }
    );
    $("#fileTable_filter").css("display", "none");
    $('#fileTable_length').css("display", "none");

    $('#filterDateFrom').datepicker().on('changeDate', function(ev){
        fileTable.fnDraw();
        $('#filterDateFrom').datepicker('hide');
    } );

    $('#filterDateTo').datepicker()
            .on('changeDate', function(ev){
                fileTable.fnDraw();
                $('#filterDateTo').datepicker('hide');
            } );

    $("#filterJob").keyup(function () { FilterChanged($("#filterJob").val(), 1); });
    $("#filterType").keyup(function () { FilterChanged($("#filterType").val(), 2); });
    $("#filterName").keyup(function () { FilterChanged($("#filterName").val(), 3); });

});
function parseDateValue(input) {
    input = input.replace('.','');
    return Date.parse(input);
}

function FilterChanged(value, column) {
    var table = $("#fileTable").dataTable();
    if (!value) value = '';
    table.fnFilter(value, column);
}

$.fn.dataTableExt.afnFiltering.push(
        function(oSettings, aData, iDataIndex){
            var dateStart =$('#filterDateFrom>input').val();
            var dateEnd =$('#filterDateTo>input').val();
            if (!dateStart && !dateEnd) return true;
            var evalDate= aData[0].substring(0,13);

            if (!dateStart) {
                if (parseDateValue(evalDate) <= parseDateValue(dateEnd)) {
                    return true;
                }
                else {
                    return false;
                }
            } else if(!dateEnd) {
                if (parseDateValue(evalDate) >= parseDateValue(dateStart)) {
                    return true;
                }
                else {
                    return false;
                }
            }

            if (parseDateValue(evalDate) >= parseDateValue(dateStart) && parseDateValue(evalDate) <=parseDateValue(dateEnd)) {
                return true;
            }
            else {
                return false;
            }

        });

function ClearFilter(){
    $('#filterDateTo>input').val('');
    $('#filterDateFrom>input').val('');
    $('#filterDateTo').data('datepicker').date = null;
    $('#filterDateFrom').data('datepicker').date = null;
    $("#filterJob").val('');
    $("#filterType").val('');
    $("#filterName").val('');

    var table = $("#fileTable").dataTable();
    var oSettings = table.fnSettings();
    for(iCol = 0; iCol < oSettings.aoPreSearchCols.length; iCol++) {
        oSettings.aoPreSearchCols[ iCol ].sSearch = '';
    }
    table.fnDraw();
}


</script>